name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: leoribg/simplicity-studio-5:latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -f empty.Makefile
    - name: binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: empty.s37
        path: ./build/debug/empty.s37
    - name: static analisys
      run: cppcheck . --output-file=cpplog.txt
    - name: lint artifact
      uses: actions/upload-artifact@v3
      with:
        name: lint_output.txt
        path: ./cpplog.txt
